using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using WildQuest.Enums;
using WildQuest.Enums.WildQuest.Enums;
using WildQuest.Interfaces;
using WildQuest.Stats;

namespace WildQuest.Items;

public static class ItemDatabase
{
    public static ConcurrentDictionary<string, IItem> Items { get; set; } = new(StringComparer.OrdinalIgnoreCase)
    {
        // Healing Items
        ["Weak Health Potion"] = new HealthItem(
            name: "Weak Health Potion",
            description: "A weak health potion that restores 25% health.",
            price: 25,
            type: ItemType.Consumable,
            healPercentage: 25,
            stackable: true,
            quantity: 1
        ),
        ["Normal Health Potion"] = new HealthItem(
            name: "Normal Health Potion",
            description: "A normal health potion that restores 50% health.",
            price: 50,
            type: ItemType.Consumable,
            healPercentage: 50,
            stackable: true,
            quantity: 1
        ),
        ["Strong Health Potion"] = new HealthItem(
            name: "Strong Health Potion",
            description: "A strong health potion that restores 75% health.",
            price: 100,
            type: ItemType.Consumable,
            healPercentage: 75,
            stackable: true,
            quantity: 1
        ),
        ["Elixir"] = new HealthItem(
            name: "Elixir",
            description: "An elixir that restores 100% health.",
            price: 200,
            type: ItemType.Consumable,
            healPercentage: 100,
            stackable: true,
            quantity: 1
        ),

        // Melee Gear - Bronze Tier
        ["Bronze Helmet"] = new ArmorItem(
            name: "Bronze Helmet",
            description: "A bronze helmet that provides 5 melee defense and -2 magic defense.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 5, 0, 0, 0, -2),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1
        ),
        ["Bronze Chestplate"] = new ArmorItem(
            name: "Bronze Chestplate",
            description: "A bronze chestplate that provides 10 melee defense and -5 magic defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 10, 0, 0, 0, -5),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1
        ),
        ["Bronze Gauntlets"] = new ArmorItem(
            name: "Bronze Gauntlets",
            description: "Bronze gauntlets that provide 3 melee defense and -1 magic defense.",
            price: 30,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 3, 0, 0, 0, -1),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1
        ),
        ["Bronze Greaves"] = new ArmorItem(
            name: "Bronze Greaves",
            description: "Bronze greaves that provide 7 melee defense and -3 magic defense.",
            price: 70,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 7, 0, 0, 0, -3),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1
        ),
        ["Bronze Dagger"] = new WeaponItem(
            name: "Bronze Dagger",
            description: "A bronze dagger that adds 3 melee attack.",
            price: 40,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 3, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Dagger,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1
        ),
        ["Bronze Sword"] = new WeaponItem(
            name: "Bronze Sword",
            description: "A bronze sword that adds 5 melee attack.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 5, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Sword,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1
        ),
        ["Bronze GreatSword"] = new WeaponItem(
            name: "Bronze GreatSword",
            description: "A bronze greatsword that adds 8 melee attack.",
            price: 70,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 8, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.GreatSword,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1
        ),
        
        // Melee Gear - Iron Tier
        ["Iron Helmet"] = new ArmorItem(
            name: "Iron Helmet",
            description: "An iron helmet that provides 8 melee defense and -3 magic defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 8, 0, 0, 0, -3),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1
        ),
        ["Iron Chestplate"] = new ArmorItem(
            name: "Iron Chestplate",
            description: "An iron chestplate that provides 15 melee defense and -7 magic defense.",
            price: 200,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 15, 0, 0, 0, -7),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1
        ),
        ["Iron Gauntlets"] = new ArmorItem(
            name: "Iron Gauntlets",
            description: "Iron gauntlets that provide 5 melee defense and -2 magic defense.",
            price: 60,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 5, 0, 0, 0, -2),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1
        ),
        ["Iron Greaves"] = new ArmorItem(
            name: "Iron Greaves",
            description: "Iron greaves that provide 10 melee defense and -5 magic defense.",
            price: 140,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 10, 0, 0, 0, -5),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1
        ),
        ["Iron Dagger"] = new WeaponItem(
            name: "Iron Dagger",
            description: "An iron dagger that adds 6 melee attack.",
            price: 80,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 6, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Dagger,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1
        ),
        ["Iron Sword"] = new WeaponItem(
            name: "Iron Sword",
            description: "An iron sword that adds 10 melee attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 10, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Sword,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1
        ),
        ["Iron GreatSword"] = new WeaponItem(
            name: "Iron GreatSword",
            description: "An iron greatsword that adds 15 melee attack.",
            price: 140,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 15, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.GreatSword,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1
        ),
        
        // Melee Gear - Steel Tier
        ["Steel Helmet"] = new ArmorItem(
            name: "Steel Helmet",
            description: "A steel helmet that provides 12 melee defense and -4 magic defense.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 12, 0, 0, 0, -4),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1
        ),
        ["Steel Chestplate"] = new ArmorItem(
            name: "Steel Chestplate",
            description: "A steel chestplate that provides 20 melee defense and -10 magic defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 20, 0, 0, 0, -10),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1
        ),
        ["Steel Gauntlets"] = new ArmorItem(
            name: "Steel Gauntlets",
            description: "Steel gauntlets that provide 7 melee defense and -3 magic defense.",
            price: 90,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 7, 0, 0, 0, -3),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1
        ),
        ["Steel Greaves"] = new ArmorItem(
            name: "Steel Greaves",
            description: "Steel greaves that provide 15 melee defense and -7 magic defense.",
            price: 180,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 15, 0, 0, 0, -7),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1
        ),
        ["Steel Dagger"] = new WeaponItem(
            name: "Steel Dagger",
            description: "A steel dagger that adds 8 melee attack.",
            price: 120,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 8, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Dagger,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1
        ),
        ["Steel Sword"] = new WeaponItem(
            name: "Steel Sword",
            description: "A steel sword that adds 12 melee attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 12, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Sword,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1
        ),
        ["Steel GreatSword"] = new WeaponItem(
            name: "Steel GreatSword",
            description: "A steel greatsword that adds 18 melee attack.",
            price: 210,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 18, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.GreatSword,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1
        ),
        
         // Mithril Gear - Mithril Tier
        ["Mithril Helmet"] = new ArmorItem(
            name: "Mithril Helmet",
            description: "A mithril helmet that provides 20 melee defense and -5 magic defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 20, 0, 0, 0, -5),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1
        ),
        ["Mithril Chestplate"] = new ArmorItem(
            name: "Mithril Chestplate",
            description: "A mithril chestplate that provides 30 melee defense and -12 magic defense.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 30, 0, 0, 0, -12),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1
        ),
        ["Mithril Gauntlets"] = new ArmorItem(
            name: "Mithril Gauntlets",
            description: "Mithril gauntlets that provide 10 melee defense and -4 magic defense.",
            price: 180,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 10, 0, 0, 0, -4),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1
        ),
        ["Mithril Greaves"] = new ArmorItem(
            name: "Mithril Greaves",
            description: "Mithril greaves that provide 20 melee defense and -10 magic defense.",
            price: 360,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 20, 0, 0, 0, -10),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1
        ),
        ["Mithril Dagger"] = new WeaponItem(
            name: "Mithril Dagger",
            description: "A mithril dagger that adds 15 melee attack.",
            price: 240,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 15, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Dagger,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1
        ),
        ["Mithril Sword"] = new WeaponItem(
            name: "Mithril Sword",
            description: "A mithril sword that adds 20 melee attack.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 20, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Sword,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1
        ),
        ["Mithril GreatSword"] = new WeaponItem(
            name: "Mithril GreatSword",
            description: "A mithril greatsword that adds 30 melee attack.",
            price: 420,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 30, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.GreatSword,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1
        ),
        
        // Dragon Gear - Dragon Tier
        ["Dragon Helmet"] = new ArmorItem(
            name: "Dragon Helmet",
            description: "A dragon helmet that provides 30 melee defense and -8 magic defense.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 30, 0, 0, 0, -8),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1
        ),
        ["Dragon Chestplate"] = new ArmorItem(
            name: "Dragon Chestplate",
            description: "A dragon chestplate that provides 40 melee defense and -15 magic defense.",
            price: 1000,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 40, 0, 0, 0, -15),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1
        ),
        ["Dragon Gauntlets"] = new ArmorItem(
            name: "Dragon Gauntlets",
            description: "Dragon gauntlets that provide 15 melee defense and -5 magic defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 15, 0, 0, 0, -5),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1
        ),
        ["Dragon Greaves"] = new ArmorItem(
            name: "Dragon Greaves",
            description: "Dragon greaves that provide 25 melee defense and -10 magic defense.",
            price: 720,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 25, 0, 0, 0, -10),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1
        ),
        ["Dragon Dagger"] = new WeaponItem(
            name: "Dragon Dagger",
            description: "A dragon dagger that adds 25 melee attack.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 25, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Dagger,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1
        ),
        ["Dragon Sword"] = new WeaponItem(
            name: "Dragon Sword",
            description: "A dragon sword that adds 30 melee attack.",
            price: 750,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 30, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Sword,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1
        ),
        ["Dragon GreatSword"] = new WeaponItem(
            name: "Dragon GreatSword",
            description: "A dragon greatsword that adds 40 melee attack.",
            price: 900,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 40, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.GreatSword,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1
        ),
        
        // Feeble Gear - Ranged Tier
        ["Feeble Feather Cap"] = new ArmorItem(
            name: "Feeble Feather Cap",
            description: "A feather cap that provides 5 ranged defense and -2 melee defense.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, 5, 0, -2),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1
        ),
        ["Feeble Leather Vest"] = new ArmorItem(
            name: "Feeble Leather Vest",
            description: "A leather vest that provides 10 ranged defense and -5 melee defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, 10, 0, -5),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1
        ),
        ["Feeble Leather Gloves"] = new ArmorItem(
            name: "Feeble Leather Gloves",
            description: "Leather gloves that provide 3 ranged defense and -1 melee defense.",
            price: 30,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, 3, 0, -1),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1
        ),
        ["Feeble Leather Boots"] = new ArmorItem(
            name: "Feeble Leather Boots",
            description: "Leather boots that provide 7 ranged defense and -3 melee defense.",
            price: 70,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, 7, 0, -3),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1
        ),
        ["Feeble ThrowingKnife"] = new WeaponItem(
            name: "Feeble ThrowingKnife",
            description: "A throwing knife that adds 5 ranged attack.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 5, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.ThrowingKnife,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1
        ),
        ["Feeble Wood Shortbow"] = new WeaponItem(
            name: "Feeble Wood Shortbow",
            description: "A wood shortbow that adds 7 ranged attack.",
            price: 70,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 7, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Bow,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1
        ),
        ["Feeble Crossbow"] = new WeaponItem(
            name: "Feeble Crossbow",
            description: "A crossbow that adds 10 ranged attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 10, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Crossbow,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1
        ),
        
        // Weak Gear - Ranged Tier
        ["Weak Feather Cap"] = new ArmorItem(
            name: "Weak Feather Cap",
            description: "A feather cap that provides 8 ranged defense and -3 melee defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, 8, 0, -3),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1
        ),
        ["Weak Leather Vest"] = new ArmorItem(
            name: "Weak Leather Vest",
            description: "A leather vest that provides 15 ranged defense and -7 melee defense.",
            price: 200,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, 15, 0, -7),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1
        ),
        ["Weak Leather Gloves"] = new ArmorItem(
            name: "Weak Leather Gloves",
            description: "Leather gloves that provide 5 ranged defense and -2 melee defense.",
            price: 60,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, 5, 0, -2),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1
        ),
        ["Weak Leather Boots"] = new ArmorItem(
            name: "Weak Leather Boots",
            description: "Leather boots that provide 10 ranged defense and -5 melee defense.",
            price: 140,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, 10, 0, -5),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1
        ),
        ["Weak ThrowingKnife"] = new WeaponItem(
            name: "Weak ThrowingKnife",
            description: "A throwing knife that adds 8 ranged attack.",
            price: 80,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 8, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.ThrowingKnife,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1
        ),
        ["Weak Wood Shortbow"] = new WeaponItem(
            name: "Weak Wood Shortbow",
            description: "A wood shortbow that adds 10 ranged attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 10, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Bow,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1
        ),
        ["Weak Crossbow"] = new WeaponItem(
            name: "Weak Crossbow",
            description: "A crossbow that adds 12 ranged attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 12, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Crossbow,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1
        ),
        
        // Strong Gear - Ranged Tier
        ["Strong Feather Cap"] = new ArmorItem(
            name: "Strong Feather Cap",
            description: "A feather cap that provides 12 ranged defense and -4 melee defense.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, 12, 0, -4),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1
        ),
        ["Strong Leather Vest"] = new ArmorItem(
            name: "Strong Leather Vest",
            description: "A leather vest that provides 20 ranged defense and -10 melee defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, 20, 0, -10),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1
        ),
        ["Strong Leather Gloves"] = new ArmorItem(
            name: "Strong Leather Gloves",
            description: "Leather gloves that provide 7 ranged defense and -3 melee defense.",
            price: 90,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, 7, 0, -3),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1
        ),
        ["Strong Leather Boots"] = new ArmorItem(
            name: "Strong Leather Boots",
            description: "Leather boots that provide 15 ranged defense and -7 melee defense.",
            price: 180,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, 15, 0, -7),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1
        ),
        ["Strong ThrowingKnife"] = new WeaponItem(
            name: "Strong ThrowingKnife",
            description: "A throwing knife that adds 12 ranged attack.",
            price: 120,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 12, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.ThrowingKnife,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1
        ),
        ["Strong Wood Shortbow"] = new WeaponItem(
            name: "Strong Wood Shortbow",
            description: "A wood shortbow that adds 15 ranged attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 15, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Bow,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1
        ),
        ["Strong Crossbow"] = new WeaponItem(
            name: "Strong Crossbow",
            description: "A crossbow that adds 20 ranged attack.",
            price: 200,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 20, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Crossbow,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1
        ),
        
         // Reinforced Gear - Ranged Tier
        ["Reinforced Feather Cap"] = new ArmorItem(
            name: "Reinforced Feather Cap",
            description: "A feather cap that provides 15 ranged defense and -5 melee defense.",
            price: 250,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, 15, 0, -5),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1
        ),
        ["Reinforced Leather Vest"] = new ArmorItem(
            name: "Reinforced Leather Vest",
            description: "A leather vest that provides 25 ranged defense and -12 melee defense.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, 25, 0, -12),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1
        ),
        ["Reinforced Leather Gloves"] = new ArmorItem(
            name: "Reinforced Leather Gloves",
            description: "Leather gloves that provide 10 ranged defense and -4 melee defense.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, 10, 0, -4),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1
        ),
        ["Reinforced Leather Boots"] = new ArmorItem(
            name: "Reinforced Leather Boots",
            description: "Leather boots that provide 20 ranged defense and -10 melee defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, 20, 0, -10),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1
        ),
        ["Reinforced ThrowingKnife"] = new WeaponItem(
            name: "Reinforced ThrowingKnife",
            description: "A throwing knife that adds 18 ranged attack.",
            price: 200,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 18, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.ThrowingKnife,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1
        ),
        ["Reinforced Wood Shortbow"] = new WeaponItem(
            name: "Reinforced Wood Shortbow",
            description: "A wood shortbow that adds 25 ranged attack.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 25, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Bow,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1
        ),
        ["Reinforced Crossbow"] = new WeaponItem(
            name: "Reinforced Crossbow",
            description: "A crossbow that adds 30 ranged attack.",
            price: 400,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 30, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Crossbow,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1
        ),
        
        // Crystal Gear - Ranged Tier
        ["Crystal Feather Cap"] = new ArmorItem(
            name: "Crystal Feather Cap",
            description: "A feather cap that provides 20 ranged defense and -6 melee defense.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, 20, 0, -6),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1
        ),
        ["Crystal Leather Vest"] = new ArmorItem(
            name: "Crystal Leather Vest",
            description: "A leather vest that provides 30 ranged defense and -15 melee defense.",
            price: 1000,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, 30, 0, -15),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1
        ),
        ["Crystal Leather Gloves"] = new ArmorItem(
            name: "Crystal Leather Gloves",
            description: "Leather gloves that provide 15 ranged defense and -5 melee defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, 15, 0, -5),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1
        ),
        ["Crystal Leather Boots"] = new ArmorItem(
            name: "Crystal Leather Boots",
            description: "Leather boots that provide 25 ranged defense and -12 melee defense.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, 25, 0, -12),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1
        ),
        ["Crystal ThrowingKnife"] = new WeaponItem(
            name: "Crystal ThrowingKnife",
            description: "A throwing knife that adds 25 ranged attack.",
            price: 400,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 25, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.ThrowingKnife,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1
        ),
        ["Crystal Wood Shortbow"] = new WeaponItem(
            name: "Crystal Wood Shortbow",
            description: "A wood shortbow that adds 30 ranged attack.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 30, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Bow,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1
        ),
        ["Crystal Crossbow"] = new WeaponItem(
            name: "Crystal Crossbow",
            description: "A crossbow that adds 40 ranged attack.",
            price: 800,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 40, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Crossbow,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1
        ),
        
        // Old Gear - Mage Tier
        ["Old Magic Hat"] = new ArmorItem(
            name: "Old Magic Hat",
            description: "A magic hat that provides 5 magic defense and -2 ranged defense.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, -2, 5, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1
        ),
        ["Old Robes"] = new ArmorItem(
            name: "Old Robes",
            description: "Robes that provide 10 magic defense and -5 ranged defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, -5, 10, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1
        ),
        ["Old Magic Gloves"] = new ArmorItem(
            name: "Old Magic Gloves",
            description: "Magic gloves that provide 3 magic defense and -1 ranged defense.",
            price: 30,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, -1, 3, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1
        ),
        ["Old Magic Boots"] = new ArmorItem(
            name: "Old Magic Boots",
            description: "Magic boots that provide 7 magic defense and -3 ranged defense.",
            price: 70,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, -3, 7, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1
        ),
        ["Old Magic Staff"] = new WeaponItem(
            name: "Old Magic Staff",
            description: "A magic staff that adds 5 magic attack.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 5, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Staff,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1
        ),
        ["Old Magic Wand"] = new WeaponItem(
            name: "Old Magic Wand",
            description: "A magic wand that adds 5 magic attack.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 5, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Wand,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1
        ),
        ["Old Grimoire"] = new WeaponItem(
            name: "Old Grimoire",
            description: "A grimoire that adds 5 magic attack.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 5, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Grimoire,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1
        ),
        
        // Worn Gear - Mage Tier
        ["Worn Magic Hat"] = new ArmorItem(
            name: "Worn Magic Hat",
            description: "A worn magic hat that provides 8 magic defense and -3 ranged defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, -3, 8, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1
        ),
        ["Worn Robes"] = new ArmorItem(
            name: "Worn Robes",
            description: "Worn robes that provide 15 magic defense and -7 ranged defense.",
            price: 200,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, -7, 15, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1
        ),
        ["Worn Magic Gloves"] = new ArmorItem(
            name: "Worn Magic Gloves",
            description: "Worn magic gloves that provide 5 magic defense and -2 ranged defense.",
            price: 60,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, -2, 5, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1
        ),
        ["Worn Magic Boots"] = new ArmorItem(
            name: "Worn Magic Boots",
            description: "Worn magic boots that provide 10 magic defense and -5 ranged defense.",
            price: 140,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, -5, 10, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1
        ),
        ["Worn Magic Staff"] = new WeaponItem(
            name: "Worn Magic Staff",
            description: "A worn magic staff that adds 8 magic attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 8, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Staff,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1
        ),
        ["Worn Magic Wand"] = new WeaponItem(
            name: "Worn Magic Wand",
            description: "A worn magic wand that adds 8 magic attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 8, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Wand,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1
        ),
        ["Worn Grimoire"] = new WeaponItem(
            name: "Worn Grimoire",
            description: "A worn grimoire that adds 8 magic attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 8, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Grimoire,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1
        ),
        
        // Enchanted Gear - Mage Tier
        ["Enchanted Magic Hat"] = new ArmorItem(
            name: "Enchanted Magic Hat",
            description: "An enchanted magic hat that provides 12 magic defense and -4 ranged defense.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, -4, 12, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1
        ),
        ["Enchanted Robes"] = new ArmorItem(
            name: "Enchanted Robes",
            description: "Enchanted robes that provide 20 magic defense and -10 ranged defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, -10, 20, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1
        ),
        ["Enchanted Magic Gloves"] = new ArmorItem(
            name: "Enchanted Magic Gloves",
            description: "Enchanted magic gloves that provide 7 magic defense and -3 ranged defense.",
            price: 90,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, -3, 7, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1
        ),
        ["Enchanted Magic Boots"] = new ArmorItem(
            name: "Enchanted Magic Boots",
            description: "Enchanted magic boots that provide 15 magic defense and -7 ranged defense.",
            price: 180,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, -7, 15, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1
        ),
        ["Enchanted Magic Staff"] = new WeaponItem(
            name: "Enchanted Magic Staff",
            description: "An enchanted magic staff that adds 12 magic attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 12, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Staff,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1
        ),
        ["Enchanted Magic Wand"] = new WeaponItem(
            name: "Enchanted Magic Wand",
            description: "An enchanted magic wand that adds 12 magic attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 12, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Wand,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1
        ),
        ["Enchanted Grimoire"] = new WeaponItem(
            name: "Enchanted Grimoire",
            description: "An enchanted grimoire that adds 12 magic attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 12, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Grimoire,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1
        ),
        
        // Arcane Gear - Mage Tier
        ["Arcane Magic Hat"] = new ArmorItem(
            name: "Arcane Magic Hat",
            description: "An arcane magic hat that provides 20 magic defense and -6 ranged defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, -6, 20, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1
        ),
        ["Arcane Robes"] = new ArmorItem(
            name: "Arcane Robes",
            description: "Arcane robes that provide 30 magic defense and -15 ranged defense.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, -15, 30, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1
        ),
        ["Arcane Magic Gloves"] = new ArmorItem(
            name: "Arcane Magic Gloves",
            description: "Arcane magic gloves that provide 15 magic defense and -5 ranged defense.",
            price: 180,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, -5, 15, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1
        ),
        ["Arcane Magic Boots"] = new ArmorItem(
            name: "Arcane Magic Boots",
            description: "Arcane magic boots that provide 25 magic defense and -10 ranged defense.",
            price: 360,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, -10, 25, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1
        ),
        ["Arcane Magic Staff"] = new WeaponItem(
            name: "Arcane Magic Staff",
            description: "An arcane magic staff that adds 20 magic attack.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 20, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Staff,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1
        ),
        ["Arcane Magic Wand"] = new WeaponItem(
            name: "Arcane Magic Wand",
            description: "An arcane magic wand that adds 20 magic attack.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 20, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Wand,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1
        ),
        ["Arcane Grimoire"] = new WeaponItem(
            name: "Arcane Grimoire",
            description: "An arcane grimoire that adds 20 magic attack.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 20, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Grimoire,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1
        ),
        
        // Mystic Gear - Mage Tier
        ["Mystic Magic Hat"] = new ArmorItem(
            name: "Mystic Magic Hat",
            description: "A mystic magic hat that provides 30 magic defense and -8 ranged defense.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, -8, 30, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1
        ),
        ["Mystic Robes"] = new ArmorItem(
            name: "Mystic Robes",
            description: "Mystic robes that provide 40 magic defense and -20 ranged defense.",
            price: 1000,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, -20, 40, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1
        ),
        ["Mystic Magic Gloves"] = new ArmorItem(
            name: "Mystic Magic Gloves",
            description: "Mystic magic gloves that provide 20 magic defense and -7 ranged defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, -7, 20, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1
        ),
        ["Mystic Magic Boots"] = new ArmorItem(
            name: "Mystic Magic Boots",
            description: "Mystic magic boots that provide 30 magic defense and -15 ranged defense.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, -15, 30, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1
        ),
        ["Mystic Magic Staff"] = new WeaponItem(
            name: "Mystic Magic Staff",
            description: "A mystic magic staff that adds 30 magic attack.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 30, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Staff,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1
        ),
        ["Mystic Magic Wand"] = new WeaponItem(
            name: "Mystic Magic Wand",
            description: "A mystic magic wand that adds 30 magic attack.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 30, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Wand,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1
        ),
        ["Mystic Grimoire"] = new WeaponItem(
            name: "Mystic Grimoire",
            description: "A mystic grimoire that adds 30 magic attack.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 30, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Grimoire,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1
        )
    };
}