using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using WildQuest.Enums;
using WildQuest.Interfaces;
using WildQuest.Items.Equipment;
using WildQuest.Items.Status;
using WildQuest.Stats;

namespace WildQuest.Items;

public static class ItemDatabase
{
    public static ConcurrentDictionary<string, IItem> Items { get; set; } = new(StringComparer.OrdinalIgnoreCase)
    {
        // Healing Items
        [ItemNames.WeakHealthPotion] = new HealthItem(
            name: ItemNames.WeakHealthPotion,
            description: "A weak health potion that restores 25% health.",
            price: 25,
            type: ItemType.Consumable,
            healPercentage: 25,
            stackable: true,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.NormalHealthPotion] = new HealthItem(
            name: ItemNames.NormalHealthPotion,
            description: "A normal health potion that restores 50% health.",
            price: 50,
            type: ItemType.Consumable,
            healPercentage: 50,
            stackable: true,
            quantity: 1,
            dropRate: 1
            
        ),
        [ItemNames.StrongHealthPotion] = new HealthItem(
            name: ItemNames.StrongHealthPotion,
            description: "A strong health potion that restores 75% health.",
            price: 100,
            type: ItemType.Consumable,
            healPercentage: 75,
            stackable: true,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.Elixir] = new HealthItem(
            name: ItemNames.Elixir,
            description: "An elixir that restores 100% health.",
            price: 200,
            type: ItemType.Consumable,
            healPercentage: 100,
            stackable: true,
            quantity: 1,
            dropRate: 1
        ),

        // Melee Gear - Bronze Tier
        [ItemNames.BronzeHelmet] = new ArmorItem(
            name: ItemNames.BronzeHelmet,
            description: "A bronze helmet that provides 5 melee defense and -2 magic defense.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 5, 0, 0, 0, -2),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.BronzeChestplate] = new ArmorItem(
            name: ItemNames.BronzeChestplate,
            description: "A bronze chestplate that provides 10 melee defense and -5 magic defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 10, 0, 0, 0, -5),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.BronzeGauntlets] = new ArmorItem(
            name: ItemNames.BronzeGauntlets,
            description: "Bronze gauntlets that provide 3 melee defense and -1 magic defense.",
            price: 30,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 3, 0, 0, 0, -1),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.BronzeGreaves] = new ArmorItem(
            name: ItemNames.BronzeGreaves,
            description: "Bronze greaves that provide 7 melee defense and -3 magic defense.",
            price: 70,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 7, 0, 0, 0, -3),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.BronzeShield] = new ArmorItem(
            name: ItemNames.BronzeShield,
            description: "A bronze shield that provides 5 melee defense and -2 magic defense.",
            price: 80,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 5, 0, 0, 0, -2),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.BronzeDagger] = new WeaponItem(
            name: ItemNames.BronzeDagger,
            description: "A bronze dagger that adds 3 melee attack.",
            price: 40,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 3, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Dagger,
            damageMultiplier: 10.00,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.BronzeSword] = new WeaponItem(
            name: ItemNames.BronzeSword,
            description: "A bronze sword that adds 5 melee attack.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 5, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Sword,
            damageMultiplier: 10.00,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.BronzeGreatSword] = new WeaponItem(
            name: ItemNames.BronzeGreatSword,
            description: "A bronze greatsword that adds 8 melee attack.",
            price: 70,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 8, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.GreatSword,
            damageMultiplier: 10.00,
            gearTier: GearTier.Bronze,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Melee Gear - Iron Tier
        [ItemNames.IronHelmet] = new ArmorItem(
            name: ItemNames.IronHelmet,
            description: "An iron helmet that provides 8 melee defense and -3 magic defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 8, 0, 0, 0, -3),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.IronChestplate] = new ArmorItem(
            name: ItemNames.IronChestplate,
            description: "An iron chestplate that provides 15 melee defense and -7 magic defense.",
            price: 200,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 15, 0, 0, 0, -7),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.IronGauntlets] = new ArmorItem(
            name: ItemNames.IronGauntlets,
            description: "Iron gauntlets that provide 5 melee defense and -2 magic defense.",
            price: 60,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 5, 0, 0, 0, -2),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.IronGreaves] = new ArmorItem(
            name: ItemNames.IronGreaves,
            description: "Iron greaves that provide 10 melee defense and -5 magic defense.",
            price: 140,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 10, 0, 0, 0, -5),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.IronShield] = new ArmorItem(
            name: ItemNames.IronShield,
            description: "An iron shield that provides 8 melee defense and -3 magic defense.",
            price: 160,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 8, 0, 0, 0, -3),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.IronDagger] = new WeaponItem(
            name: ItemNames.IronDagger,
            description: "An iron dagger that adds 6 melee attack.",
            price: 80,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 6, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Dagger,
            damageMultiplier: 10.00,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.IronSword] = new WeaponItem(
            name: ItemNames.IronSword,
            description: "An iron sword that adds 10 melee attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 10, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Sword,
            damageMultiplier: 10.00,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.IronGreatSword] = new WeaponItem(
            name: ItemNames.IronGreatSword,
            description: "An iron greatsword that adds 15 melee attack.",
            price: 140,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 15, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.GreatSword,
            damageMultiplier: 10.00,
            gearTier: GearTier.Iron,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Melee Gear - Steel Tier
        [ItemNames.SteelHelmet] = new ArmorItem(
            name: ItemNames.SteelHelmet,
            description: "A steel helmet that provides 12 melee defense and -4 magic defense.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 12, 0, 0, 0, -4),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.SteelChestplate] = new ArmorItem(
            name: ItemNames.SteelChestplate,
            description: "A steel chestplate that provides 20 melee defense and -10 magic defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 20, 0, 0, 0, -10),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.SteelGauntlets] = new ArmorItem(
            name: ItemNames.SteelGauntlets,
            description: "Steel gauntlets that provide 7 melee defense and -3 magic defense.",
            price: 90,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 7, 0, 0, 0, -3),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.SteelGreaves] = new ArmorItem(
            name: ItemNames.SteelGreaves,
            description: "Steel greaves that provide 15 melee defense and -7 magic defense.",
            price: 180,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 15, 0, 0, 0, -7),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.SteelShield] = new ArmorItem(
            name: ItemNames.SteelShield,
            description: "A steel shield that provides 12 melee defense and -4 magic defense.",
            price: 200,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 12, 0, 0, 0, -4),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.SteelDagger] = new WeaponItem(
            name: ItemNames.SteelDagger,
            description: "A steel dagger that adds 8 melee attack.",
            price: 120,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 8, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Dagger,
            damageMultiplier: 10.00,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.SteelSword] = new WeaponItem(
            name: ItemNames.SteelSword,
            description: "A steel sword that adds 12 melee attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 12, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Sword,
            damageMultiplier: 10.00,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1
        ),
        [ItemNames.SteelGreatSword] = new WeaponItem(
            name: ItemNames.SteelGreatSword,
            description: "A steel greatsword that adds 18 melee attack.",
            price: 210,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 18, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.GreatSword,
            damageMultiplier: 10.00,
            gearTier: GearTier.Steel,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Mithril Gear - Mithril Tier
        [ItemNames.MithrilHelmet] = new ArmorItem(
            name: ItemNames.MithrilHelmet,
            description: "A mithril helmet that provides 20 melee defense and -5 magic defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 20, 0, 0, 0, -5),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MithrilChestplate] = new ArmorItem(
            name: ItemNames.MithrilChestplate,
            description: "A mithril chestplate that provides 30 melee defense and -12 magic defense.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 30, 0, 0, 0, -12),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MithrilGauntlets] = new ArmorItem(
            name: ItemNames.MithrilGauntlets,
            description: "Mithril gauntlets that provide 10 melee defense and -4 magic defense.",
            price: 180,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 10, 0, 0, 0, -4),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MithrilGreaves] = new ArmorItem(
            name: ItemNames.MithrilGreaves,
            description: "Mithril greaves that provide 20 melee defense and -10 magic defense.",
            price: 360,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 20, 0, 0, 0, -10),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MithrilShield] = new ArmorItem(
            name: ItemNames.MithrilShield,
            description: "A mithril shield that provides 20 melee defense and -5 magic defense.",
            price: 400,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 20, 0, 0, 0, -5),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MithrilDagger] = new WeaponItem(
            name: ItemNames.MithrilDagger,
            description: "A mithril dagger that adds 15 melee attack.",
            price: 240,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 15, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Dagger,
            damageMultiplier: 10.00,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MithrilSword] = new WeaponItem(
            name: ItemNames.MithrilSword,
            description: "A mithril sword that adds 20 melee attack.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 20, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Sword,
            damageMultiplier: 10.00,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MithrilGreatSword] = new WeaponItem(
            name: ItemNames.MithrilGreatSword,
            description: "A mithril greatsword that adds 30 melee attack.",
            price: 420,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 30, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.GreatSword,
            damageMultiplier: 10.00,
            gearTier: GearTier.Mithril,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Dragon Gear - Dragon Tier
        [ItemNames.DragonHelmet] = new ArmorItem(
            name: ItemNames.DragonHelmet,
            description: "A dragon helmet that provides 30 melee defense and -8 magic defense.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 30, 0, 0, 0, -8),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.DragonChestplate] = new ArmorItem(
            name: ItemNames.DragonChestplate,
            description: "A dragon chestplate that provides 40 melee defense and -15 magic defense.",
            price: 1000,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 40, 0, 0, 0, -15),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.DragonGauntlets] = new ArmorItem(
            name: ItemNames.DragonGauntlets,
            description: "Dragon gauntlets that provide 15 melee defense and -5 magic defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 15, 0, 0, 0, -5),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.DragonGreaves] = new ArmorItem(
            name: ItemNames.DragonGreaves,
            description: "Dragon greaves that provide 25 melee defense and -10 magic defense.",
            price: 720,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 25, 0, 0, 0, -10),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.DragonShield] = new ArmorItem(
            name: ItemNames.DragonShield,
            description: "A dragon shield that provides 30 melee defense and -8 magic defense.",
            price: 800,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 30, 0, 0, 0, -8),
            combatStyle: CombatStyle.Melee,
            armorType: ArmorType.Heavy,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.DragonDagger] = new WeaponItem(
            name: ItemNames.DragonDagger,
            description: "A dragon dagger that adds 25 melee attack.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 25, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Dagger,
            damageMultiplier: 10.00,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.DragonSword] = new WeaponItem(
            name: ItemNames.DragonSword,
            description: "A dragon sword that adds 30 melee attack.",
            price: 750,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 30, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.Sword,
            damageMultiplier: 10.00,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.DragonGreatSword] = new WeaponItem(
            name: ItemNames.DragonGreatSword,
            description: "A dragon greatsword that adds 40 melee attack.",
            price: 900,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 40, 0, 0, 0, 0, 0),
            combatStyle: CombatStyle.Melee,
            weaponType: WeaponType.GreatSword,
            damageMultiplier: 10.00,
            gearTier: GearTier.Dragon,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Feeble Gear - Ranged Tier
        [ItemNames.FeebleFeatherCap] = new ArmorItem(
            name: ItemNames.FeebleFeatherCap,
            description: "A feather cap that provides 5 ranged defense and -2 melee defense.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, 5, 0, -2),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.FeebleLeatherVest] = new ArmorItem(
            name: ItemNames.FeebleLeatherVest,
            description: "A leather vest that provides 10 ranged defense and -5 melee defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, 10, 0, -5),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.FeebleLeatherGloves] = new ArmorItem(
            name: ItemNames.FeebleLeatherGloves,
            description: "Leather gloves that provide 3 ranged defense and -1 melee defense.",
            price: 30,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, 3, 0, -1),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.FeebleLeatherBoots] = new ArmorItem(
            name: ItemNames.FeebleLeatherBoots,
            description: "Leather boots that provide 7 ranged defense and -3 melee defense.",
            price: 70,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, 7, 0, -3),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.FeebleThrowingKnife] = new WeaponItem(
            name: ItemNames.FeebleThrowingKnife,
            description: "A throwing knife that adds 5 ranged attack.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 5, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.ThrowingKnife,
            damageMultiplier: 10.00,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.FeebleWoodShortbow] = new WeaponItem(
            name: ItemNames.FeebleWoodShortbow,
            description: "A wood shortbow that adds 7 ranged attack.",
            price: 70,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 7, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Bow,
            damageMultiplier: 10.00,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.FeebleCrossbow] = new WeaponItem(
            name: ItemNames.FeebleCrossbow,
            description: "A crossbow that adds 10 ranged attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 10, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Crossbow,
            damageMultiplier: 10.00,
            gearTier: GearTier.Feeble,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Weak Gear - Ranged Tier
        [ItemNames.WeakFeatherCap] = new ArmorItem(
            name: ItemNames.WeakFeatherCap,
            description: "A feather cap that provides 8 ranged defense and -3 melee defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, 8, 0, -3),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WeakLeatherVest] = new ArmorItem(
            name: ItemNames.WeakLeatherVest,
            description: "A leather vest that provides 15 ranged defense and -7 melee defense.",
            price: 200,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, 15, 0, -7),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WeakLeatherGloves] = new ArmorItem(
            name: ItemNames.WeakLeatherGloves,
            description: "Leather gloves that provide 5 ranged defense and -2 melee defense.",
            price: 60,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, 5, 0, -2),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WeakLeatherBoots] = new ArmorItem(
            name: ItemNames.WeakLeatherBoots,
            description: "Leather boots that provide 10 ranged defense and -5 melee defense.",
            price: 140,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, 10, 0, -5),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WeakThrowingKnife] = new WeaponItem(
            name: ItemNames.WeakThrowingKnife,
            description: "A throwing knife that adds 8 ranged attack.",
            price: 80,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 8, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.ThrowingKnife,
            damageMultiplier: 10.00,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WeakWoodShortbow] = new WeaponItem(
            name: ItemNames.WeakWoodShortbow,
            description: "A wood shortbow that adds 10 ranged attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 10, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Bow,
            damageMultiplier: 10.00,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WeakCrossbow] = new WeaponItem(
            name: ItemNames.WeakCrossbow,
            description: "A crossbow that adds 12 ranged attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 12, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Crossbow,
            damageMultiplier: 10.00,
            gearTier: GearTier.Weak,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Strong Gear - Ranged Tier
        [ItemNames.StrongFeatherCap] = new ArmorItem(
            name: ItemNames.StrongFeatherCap,
            description: "A feather cap that provides 12 ranged defense and -4 melee defense.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, 12, 0, -4),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.StrongLeatherVest] = new ArmorItem(
            name: ItemNames.StrongLeatherVest,
            description: "A leather vest that provides 20 ranged defense and -10 melee defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, 20, 0, -10),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.StrongLeatherGloves] = new ArmorItem(
            name: ItemNames.StrongLeatherGloves,
            description: "Leather gloves that provide 7 ranged defense and -3 melee defense.",
            price: 90,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, 7, 0, -3),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.StrongLeatherBoots] = new ArmorItem(
            name: ItemNames.StrongLeatherBoots,
            description: "Leather boots that provide 15 ranged defense and -7 melee defense.",
            price: 180,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, 15, 0, -7),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.StrongThrowingKnife] = new WeaponItem(
            name: ItemNames.StrongThrowingKnife,
            description: "A throwing knife that adds 12 ranged attack.",
            price: 120,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 12, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.ThrowingKnife,
            damageMultiplier: 10.00,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.StrongWoodShortbow] = new WeaponItem(
            name: ItemNames.StrongWoodShortbow,
            description: "A wood shortbow that adds 15 ranged attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 15, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Bow,
            damageMultiplier: 10.00,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.StrongCrossbow] = new WeaponItem(
            name: ItemNames.StrongCrossbow,
            description: "A crossbow that adds 20 ranged attack.",
            price: 200,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 20, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Crossbow,
            damageMultiplier: 10.00,
            gearTier: GearTier.Strong,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Reinforced Gear - Ranged Tier
        [ItemNames.ReinforcedFeatherCap] = new ArmorItem(
            name: ItemNames.ReinforcedFeatherCap,
            description: "A feather cap that provides 15 ranged defense and -5 melee defense.",
            price: 250,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, 15, 0, -5),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ReinforcedLeatherVest] = new ArmorItem(
            name: ItemNames.ReinforcedLeatherVest,
            description: "A leather vest that provides 25 ranged defense and -12 melee defense.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, 25, 0, -12),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ReinforcedLeatherGloves] = new ArmorItem(
            name: ItemNames.ReinforcedLeatherGloves,
            description: "Leather gloves that provide 10 ranged defense and -4 melee defense.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, 10, 0, -4),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ReinforcedLeatherBoots] = new ArmorItem(
            name: ItemNames.ReinforcedLeatherBoots,
            description: "Leather boots that provide 20 ranged defense and -10 melee defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, 20, 0, -10),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ReinforcedThrowingKnife] = new WeaponItem(
            name: ItemNames.ReinforcedThrowingKnife,
            description: "A throwing knife that adds 18 ranged attack.",
            price: 200,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 18, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.ThrowingKnife,
            damageMultiplier: 10.00,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ReinforcedWoodShortbow] = new WeaponItem(
            name: ItemNames.ReinforcedWoodShortbow,
            description: "A wood shortbow that adds 25 ranged attack.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 25, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Bow,
            damageMultiplier: 10.00,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ReinforcedCrossbow] = new WeaponItem(
            name: ItemNames.ReinforcedCrossbow,
            description: "A crossbow that adds 30 ranged attack.",
            price: 400,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 30, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Crossbow,
            damageMultiplier: 10.00,
            gearTier: GearTier.Reinforced,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Crystal Gear - Ranged Tier
        [ItemNames.CrystalFeatherCap] = new ArmorItem(
            name: ItemNames.CrystalFeatherCap,
            description: "A feather cap that provides 20 ranged defense and -6 melee defense.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, 20, 0, -6),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.CrystalLeatherVest] = new ArmorItem(
            name: ItemNames.CrystalLeatherVest,
            description: "A leather vest that provides 30 ranged defense and -15 melee defense.",
            price: 1000,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, 30, 0, -15),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.CrystalLeatherGloves] = new ArmorItem(
            name: ItemNames.CrystalLeatherGloves,
            description: "Leather gloves that provide 15 ranged defense and -5 melee defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, 15, 0, -5),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.CrystalLeatherBoots] = new ArmorItem(
            name: ItemNames.CrystalLeatherBoots,
            description: "Leather boots that provide 25 ranged defense and -12 melee defense.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, 25, 0, -12),
            combatStyle: CombatStyle.Ranged,
            armorType: ArmorType.Light,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.CrystalThrowingKnife] = new WeaponItem(
            name: ItemNames.CrystalThrowingKnife,
            description: "A throwing knife that adds 25 ranged attack.",
            price: 400,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 25, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.ThrowingKnife,
            damageMultiplier: 10.00,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.CrystalWoodShortbow] = new WeaponItem(
            name: ItemNames.CrystalWoodShortbow,
            description: "A wood shortbow that adds 30 ranged attack.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 30, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            damageMultiplier: 10.00,
            weaponType: WeaponType.Bow,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.CrystalCrossbow] = new WeaponItem(
            name: ItemNames.CrystalCrossbow,
            description: "A crossbow that adds 40 ranged attack.",
            price: 800,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 40, 0, 0, 0),
            combatStyle: CombatStyle.Ranged,
            weaponType: WeaponType.Crossbow,
            damageMultiplier: 10.00,
            gearTier: GearTier.Crystal,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Old Gear - Mage Tier
        [ItemNames.OldMagicHat] = new ArmorItem(
            name: ItemNames.OldMagicHat,
            description: "A magic hat that provides 5 magic defense and -2 ranged defense.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, -2, 5, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.OldRobes] = new ArmorItem(
            name: ItemNames.OldRobes,
            description: "Robes that provide 10 magic defense and -5 ranged defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, -5, 10, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.OldMagicGloves] = new ArmorItem(
            name: ItemNames.OldMagicGloves,
            description: "Magic gloves that provide 3 magic defense and -1 ranged defense.",
            price: 30,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, -1, 3, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.OldMagicBoots] = new ArmorItem(
            name: ItemNames.OldMagicBoots,
            description: "Magic boots that provide 7 magic defense and -3 ranged defense.",
            price: 70,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, -3, 7, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.OldMagicStaff] = new WeaponItem(
            name: ItemNames.OldMagicStaff,
            description: "A magic staff that adds 5 magic attack.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 5, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Staff,
            damageMultiplier: 10.00,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.OldMagicWand] = new WeaponItem(
            name: ItemNames.OldMagicWand,
            description: "A magic wand that adds 5 magic attack.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 5, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Wand,
            damageMultiplier: 10.00,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.OldGrimoire] = new WeaponItem(
            name: ItemNames.OldGrimoire,
            description: "A grimoire that adds 5 magic attack.",
            price: 50,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 5, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Grimoire,
            damageMultiplier: 10.00,
            gearTier: GearTier.Old,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Worn Gear - Mage Tier
        [ItemNames.WornMagicHat] = new ArmorItem(
            name: ItemNames.WornMagicHat,
            description: "A worn magic hat that provides 8 magic defense and -3 ranged defense.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, -3, 8, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WornRobes] = new ArmorItem(
            name: ItemNames.WornRobes,
            description: "Worn robes that provide 15 magic defense and -7 ranged defense.",
            price: 200,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, -7, 15, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WornMagicGloves] = new ArmorItem(
            name: ItemNames.WornMagicGloves,
            description: "Worn magic gloves that provide 5 magic defense and -2 ranged defense.",
            price: 60,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, -2, 5, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WornMagicBoots] = new ArmorItem(
            name: ItemNames.WornMagicBoots,
            description: "Worn magic boots that provide 10 magic defense and -5 ranged defense.",
            price: 140,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, -5, 10, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WornMagicStaff] = new WeaponItem(
            name: ItemNames.WornMagicStaff,
            description: "A worn magic staff that adds 8 magic attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 8, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Staff,
            damageMultiplier: 10.00,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WornMagicWand] = new WeaponItem(
            name: ItemNames.WornMagicWand,
            description: "A worn magic wand that adds 8 magic attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 8, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Wand,
            damageMultiplier: 10.00,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.WornGrimoire] = new WeaponItem(
            name: ItemNames.WornGrimoire,
            description: "A worn grimoire that adds 8 magic attack.",
            price: 100,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 8, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Grimoire,
            damageMultiplier: 10.00,
            gearTier: GearTier.Worn,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Enchanted Gear - Mage Tier
        [ItemNames.EnchantedMagicHat] = new ArmorItem(
            name: ItemNames.EnchantedMagicHat,
            description: "An enchanted magic hat that provides 12 magic defense and -4 ranged defense.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, -4, 12, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.EnchantedRobes] = new ArmorItem(
            name: ItemNames.EnchantedRobes,
            description: "Enchanted robes that provide 20 magic defense and -10 ranged defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, -10, 20, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.EnchantedMagicGloves] = new ArmorItem(
            name: ItemNames.EnchantedMagicGloves,
            description: "Enchanted magic gloves that provide 7 magic defense and -3 ranged defense.",
            price: 90,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, -3, 7, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.EnchantedMagicBoots] = new ArmorItem(
            name: ItemNames.EnchantedMagicBoots,
            description: "Enchanted magic boots that provide 15 magic defense and -7 ranged defense.",
            price: 180,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, -7, 15, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.EnchantedMagicStaff] = new WeaponItem(
            name: ItemNames.EnchantedMagicStaff,
            description: "An enchanted magic staff that adds 12 magic attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 12, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Staff,
            damageMultiplier: 10.00,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.EnchantedMagicWand] = new WeaponItem(
            name: ItemNames.EnchantedMagicWand,
            description: "An enchanted magic wand that adds 12 magic attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 12, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Wand,
            damageMultiplier: 10.00,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.EnchantedGrimoire] = new WeaponItem(
            name: ItemNames.EnchantedGrimoire,
            description: "An enchanted grimoire that adds 12 magic attack.",
            price: 150,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 12, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Grimoire,
            damageMultiplier: 10.00,
            gearTier: GearTier.Enchanted,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Arcane Gear - Mage Tier
        [ItemNames.ArcaneMagicHat] = new ArmorItem(
            name: ItemNames.ArcaneMagicHat,
            description: "An arcane magic hat that provides 20 magic defense and -6 ranged defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, -6, 20, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ArcaneRobes] = new ArmorItem(
            name: ItemNames.ArcaneRobes,
            description: "Arcane robes that provide 30 magic defense and -15 ranged defense.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, -15, 30, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ArcaneMagicGloves] = new ArmorItem(
            name: ItemNames.ArcaneMagicGloves,
            description: "Arcane magic gloves that provide 15 magic defense and -5 ranged defense.",
            price: 180,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, -5, 15, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ArcaneMagicBoots] = new ArmorItem(
            name: ItemNames.ArcaneMagicBoots,
            description: "Arcane magic boots that provide 25 magic defense and -10 ranged defense.",
            price: 360,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, -10, 25, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ArcaneMagicStaff] = new WeaponItem(
            name: ItemNames.ArcaneMagicStaff,
            description: "An arcane magic staff that adds 20 magic attack.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 20, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Staff,
            damageMultiplier: 10.00,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ArcaneMagicWand] = new WeaponItem(
            name: ItemNames.ArcaneMagicWand,
            description: "An arcane magic wand that adds 20 magic attack.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 20, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Wand,
            damageMultiplier: 10.00,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.ArcaneGrimoire] = new WeaponItem(
            name: ItemNames.ArcaneGrimoire,
            description: "An arcane grimoire that adds 20 magic attack.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 20, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Grimoire,
            damageMultiplier: 10.00,
            gearTier: GearTier.Arcane,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        
        // Mystic Gear - Mage Tier
        [ItemNames.MysticMagicHat] = new ArmorItem(
            name: ItemNames.MysticMagicHat,
            description: "A mystic magic hat that provides 30 magic defense and -8 ranged defense.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Head },
            stats: new ActorStats(0, 0, 0, 0, -8, 30, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MysticRobes] = new ArmorItem(
            name: ItemNames.MysticRobes,
            description: "Mystic robes that provide 40 magic defense and -20 ranged defense.",
            price: 1000,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Body },
            stats: new ActorStats(0, 0, 0, 0, -20, 40, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MysticMagicGloves] = new ArmorItem(
            name: ItemNames.MysticMagicGloves,
            description: "Mystic magic gloves that provide 20 magic defense and -7 ranged defense.",
            price: 300,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Hands },
            stats: new ActorStats(0, 0, 0, 0, -7, 20, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MysticMagicBoots] = new ArmorItem(
            name: ItemNames.MysticMagicBoots,
            description: "Mystic magic boots that provide 30 magic defense and -15 ranged defense.",
            price: 600,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.Feet },
            stats: new ActorStats(0, 0, 0, 0, -15, 30, 0),
            combatStyle: CombatStyle.Magic,
            armorType: ArmorType.Cloth,
            damageReductionMultiplier: 10.00,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MysticMagicStaff] = new WeaponItem(
            name: ItemNames.MysticMagicStaff,
            description: "A mystic magic staff that adds 30 magic attack.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand, EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 30, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Staff,
            damageMultiplier: 10.00,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MysticMagicWand] = new WeaponItem(
            name: ItemNames.MysticMagicWand,
            description: "A mystic magic wand that adds 30 magic attack.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.MainHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 30, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Wand,
            damageMultiplier: 10.00,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1,
            dropRate: 1
        ),
        [ItemNames.MysticGrimoire] = new WeaponItem(
            name: ItemNames.MysticGrimoire,
            description: "A mystic grimoire that adds 30 magic attack.",
            price: 500,
            type: ItemType.NonConsumable,
            slots: new List<EquipmentSlot> { EquipmentSlot.OffHand },
            stats: new ActorStats(0, 0, 0, 0, 0, 30, 0),
            combatStyle: CombatStyle.Magic,
            weaponType: WeaponType.Grimoire,
            damageMultiplier: 10.00,
            gearTier: GearTier.Mystic,
            stackable: false,
            quantity: 1,
            dropRate: 1
        )
    };

    public static IItem GetItems (string itemName, long quantity = 1)
    {
        if (Items.TryGetValue(itemName, out var item))
        {
            var newItem = item.Copy();
            newItem.Quantity = quantity;
            return newItem;
        }

        throw new KeyNotFoundException($"Item '{itemName}' not found in the database.");
    }
    
    public static IDropItem GetDropItems (string itemName, long quantity = 1, double dropRate = 1)
    {
        var item = GetItems(itemName, quantity);
        return new DropItem(item, dropRate);
    }

}
